name: check_vpn
description: This package helps you to fight against IP fraud & much more. This app uses an API from VPNAPI.io to stop illegal actions on applications.
version: 0.0.1
homepage: https://github.com/dharambudh1/check_vpn

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null